---
output:
  word_document: default
  html_document: default
---
#Course Prject
##John Murphy



```{r results='hide'}
library(tidyverse)
library(skimr)
library(GGally) 
library(ggcorrplot) 
library(gridExtra) 
```

```{r results='hide'}
ames <- read_csv("ames_student-1.csv")
```

```{r}
ames <- ames %>%
  mutate(Bedroom_AbvGr = as_factor(Bedroom_AbvGr)) %>%
  mutate(Half_Bath = as_factor(Half_Bath)) %>% mutate(Garage_Cars = as_factor(Garage_Cars))
```


```{r results='hide'}
skim(ames)
```

```{r}
Ames_Subset1 <- ames %>% 
  select("MS_SubClass", "Lot_Area", "Above_Median", "Neighborhood", "Bldg_Type", "House_Style", "Overall_Qual", "Overall_Cond", "Year_Built",
         "Year_Remod_Add", "Full_Bath", "Half_Bath", "Bedroom_AbvGr", "Garage_Type", "Fence", "Pool_QC")
```

```{r results='hide'}
str(Ames_Subset1)
summary(Ames_Subset1)
```

```{r}
Ames_Subset1 %>%
  filter(Lot_Area < 60000) %>%
  ggplot(aes(Lot_Area)) + 
  geom_histogram(aes(y = ..density..), binwidth = 1000, color = "black", fill = "white") +
  geom_density(lwd = 1, colour = 4, fill = 4, alpha = 0.25) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  labs(x = "Lot Area Size", y = NULL,
       title = "Frequency of Houses by Lot Area",
       subtitle = "Many Large Outliers Exist Outside of 20000") 

```

```{r}
ames %>%
  filter(Lot_Area < 60000) %>%
  ggplot(aes(x = Above_Median, y = Lot_Area, color = Lot_Shape)) + geom_point(size = 3, alpha = .5) + theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  labs(y = "Lot Area Size", x = "Above Median Price",
       title = "Lot Area Size Vs Shape",
       subtitle = "Regular lot shapes are more frequent below the median") +
  guides(color = guide_legend(title = "Lot Shape"))
```


```{r}
  Ames_Subset2 <- ames %>%
  select("Lot_Area", "Year_Built", "First_Flr_SF", "Second_Flr_SF", "Total_Bsmt_SF", "Garage_Area", "Above_Median")
```

```{r}
ggpairs(Ames_Subset2)
```

```{r}
p1 = ggplot(ames, aes(x=Above_Median, y = First_Flr_SF, color = Bedroom_AbvGr)) + geom_point(alpha=0.2) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  labs(y = "First Floor Square Footage", x = "Above Median Price",
       title = "1st Floor Square Footage") +
  guides(color = guide_legend(title = "Number Of Bedrooms"))

p2 = ggplot(ames, aes(x=Above_Median, y = Second_Flr_SF, color = Bedroom_AbvGr)) + geom_point(alpha=0.2) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  labs(y = "Second Floor Square Footage", x = "Above Median Price",
       title = "2nd Floor Square Footage") +
  guides(color = guide_legend(title = "Number Of Bedrooms"))

grid.arrange(p1,p2,ncol=2)
```

```{r}
ames %>%
  mutate(Decade_Built = ifelse(ames$Year_Built %in% 1870:1879, "1870",
                         ifelse(ames$Year_Built %in% 1880:1889, "1880",
                         ifelse(ames$Year_Built %in% 1890:1899, "1890",
                         ifelse(ames$Year_Built %in% 1900:1909, "1900",
                         ifelse(ames$Year_Built %in% 1910:1919, "1910",
                         ifelse(ames$Year_Built %in% 1920:1929, "1920",
                         ifelse(ames$Year_Built %in% 1930:1939, "1930",
                         ifelse(ames$Year_Built %in% 1940:1949, "1940",
                         ifelse(ames$Year_Built %in% 1950:1959, "1950",
                         ifelse(ames$Year_Built %in% 1960:1969, "1960",
                         ifelse(ames$Year_Built %in% 1970:1979, "1970",
                         ifelse(ames$Year_Built %in% 1980:1989, "1980",
                         ifelse(ames$Year_Built %in% 1990:1999, "1990",
                         ifelse(ames$Year_Built %in% 2000:2009, "2000",
                         ifelse(ames$Year_Built %in% 2010:2019, "2010",
                         "NA")))))))))))))))) %>%
  ggplot(aes(x = Decade_Built, fill = Above_Median)) + geom_bar() +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  labs(y = "Number of Houses", x = "Decade Built",
       title = "House Prices by Decade Built",
       subtitle = "Newer Houses are more likely to be above the Median Price") +
  guides(fill = guide_legend(title = "Above Median Price"))
```

```{r}
ames%>% 
  ggplot(aes(x = Bedroom_AbvGr, fill = Above_Median)) + geom_bar() +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  labs(y = "Number of Houses", x = "Number of Bedrooms",
       title = "House Prices by Decade Built",
       subtitle = "Houses with three or more bedrooms are more expensive") +
  guides(fill = guide_legend(title = "Above Median Price"))
```

