```{r}
library(tidyverse)
library(tidymodels)
library(e1071)
library(ROCR)
```

```{r}
credit<- read_csv("CSData-1.csv")
```

```{r}
str(credit)
summary(credit)
```

```{r}
credit = credit %>% mutate(SeriousDlqin2yrs = as_factor(SeriousDlqin2yrs)) %>%
  mutate(SeriousDlqin2yrs = fct_recode(SeriousDlqin2yrs, "No" = "0", "Yes" = "1"))

str(credit)
```

```{r}
credit = credit %>% filter(RevolvingUtilizationOfUnsecuredLines < 2) %>%
  filter(DebtRatio < 5) %>%
  filter(MonthlyIncome < 2000) %>% drop_na() %>%
  filter(NumberOfOpenCreditLinesAndLoans < 40) %>%
  filter(NumberRealEstateLoansOrLines < 10) %>%
  filter(NumberOfDependents < 10)
```

```{r}
credit_model = 
  logistic_reg(mode = "classification") %>%
  set_engine("glm")

credit_recipe = recipe(SeriousDlqin2yrs ~., credit)

logreg_wf = workflow() %>%
  add_recipe(credit_recipe) %>%
  add_model(credit_model)

credit_fit = fit(logreg_wf, credit)
```

```{r}
predictions = predict(credit_fit, credit, type="prob")
head(predictions)
```

```{r}
predictions = predict(credit_fit, credit, type="prob")[2]
head(predictions)
```

```{r}
ROCRpred = prediction(predictions, credit$SeriousDlqin2yrs)

ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
```

```{r}
as.numeric(performance(ROCRpred, "auc")@y.values)
```

```{r}
opt.cut = function(perf, pred){
  cut.ind = mapply(FUN=function(x, y, p){
    d = (x - 0)^2 + (y-1)^2
    ind = which(d == min(d))
    c(senitivity = y[[ind]], specificity = 1-x[[ind]],
      cutoff = p[[ind]])
  }, perf@x.values, perf@y.values, pred@cutoffs)
}
print(opt.cut(ROCRperf, ROCRpred))
```

```{r}
t1 = table(credit$SeriousDlqin2yrs,predictions > 0.1280821)
t1
```
accuracy
```{r}
(t1[1,1]+t1[2+2])/nrow(credit)
```

sensitivity
```{r}
588 / (233+588)
```

specificity
```{r}
5694 / (5694 + 2085)
```

