```{r}
library(tidyverse)
library(tidymodels)
library(e1071)
library(ROCR)
library(glmnet)
```

```{r}
parole <- read_csv("parole.csv")
```

```{r}
violator <- parole %>% 
  select(violator)

sum(violator)
```


```{r}
parole <- parole %>% mutate(violator = as_factor(violator)) %>%
  mutate(violator = fct_recode(violator, "No" = "0", "Yes" = "1")) %>%
  mutate(state = as_factor(state)) %>% mutate(male = as_factor(male)) %>%
  mutate(max.sentence = as.factor(max.sentence)) %>%
  mutate(race = as.factor(race)) %>%
  mutate(multiple.offenses = as.factor(multiple.offenses))
```
```{r}
set.seed(12345)
parole_split <- initial_split(parole, prop = .70, strata = violator)
train <- training(parole_split)
test <- testing(parole_split)
```

```{r}
ggplot(parole, aes(x = violator, fill = male)) + 
  geom_bar()
```

```{r}
ggplot(parole, aes(x = violator, fill = state)) + 
  geom_bar()
```

```{r}
ggplot(parole, aes(x = violator, fill = max.sentence)) + 
  geom_bar()
```

```{r}
parole_model = 
  logistic_reg(mode = "classification") %>%
  set_engine("glm")

parole_recipe = recipe(violator ~ state, train)

logreg_wf = workflow() %>%
  add_recipe(parole_recipe) %>%
  add_model(parole_model)

parole_fit = fit(logreg_wf, train)
```

```{r}
summary(parole_fit$fit$fit$fit)
```

```{r}
parole_train_model = 
  logistic_reg(mode = "classification") %>%
  set_engine("glm")

parole_train_recipe = recipe(violator ~ state + race + multiple.offenses, train)

logreg_train_wf = workflow() %>%
  add_recipe(parole_train_recipe) %>%
  add_model(parole_train_model)

parole_train_fit = fit(logreg_train_wf, train)
```

```{r}
summary(parole_train_fit$fit$fit$fit)
```


```{r}
str(train)
```


```{r}
newdata = data.frame(state = "3", multiple.offenses = "1", race = "1")
predict(parole_train_fit, newdata, type="prob")
```

```{r}
parole$multiple.offenses
```

```{r}
predictions = predict(parole_train_fit, train, type="prob")[2]
head(predictions)
```


```{r}
ROCRpred = prediction(predictions, train$violator)

ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
```

```{r}
as.numeric(performance(ROCRpred, "auc")@y.values)
```


```{r}
opt.cut = function(perf, pred){
  cut.ind = mapply(FUN=function(x, y, p){
    d = (x - 0)^2 + (y-1)^2
    ind = which(d == min(d))
    c(senitivity = y[[ind]], specificity = 1-x[[ind]],
      cutoff = p[[ind]])
  }, perf@x.values, perf@y.values, pred@cutoffs)
}
print(opt.cut(ROCRperf, ROCRpred))
```

```{r}
t1 = table(train$violator,predictions > 0.2015788)
t1
```

```{r}
36 / (18 + 36)
```

```{r}
(t1[1,1]+t1[2+2])/nrow(train)
```

```{r}
t1 = table(train$violator,predictions > 0.5)
t1
(t1[1,1]+t1[2,2])/nrow(train)
```

```{r}
19 / (35 + 19)
```

```{r}
t2 = table(test$violator,predictions > 0.5)
t2
(t2[1,1]+t2[2,2])/nrow(test)
```

```{r}
t2 = table(train$violator,predictions > 0.5)
t2
```
```{r}
(t2[1,1]+t2[2+2])/nrow(train)
```

